### ISSUE TITLE
Word movement keys in pdb++

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#58]
Originally reported by: **zakandrewking (Bitbucket: [zakandrewking](https://bitbucket.org/zakandrewking), GitHub: [zakandrewking](https://github.com/zakandrewking))**

----------------------------------------

I am accustomed to using M-f and M-b for word movement in the terminal (zsh, IPython), so I have M-right arrow and M-left arrow mapped to other things. However, pdb++ does not recognize M-f and M-b. I have tested both Python 2.7.11 and 3.5.1 with pdbpp==0.8.3.

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/58

**Comment by antocuni** [comment]
*Original comment by* **David Szotten (Bitbucket: [davidszotten](https://bitbucket.org/davidszotten), GitHub: [davidszotten](https://github.com/davidszotten))**:

----------------------------------------

This is an issue a few dependencies down (pdbpp depends on fancycompleter which depends on pyrepl)

It's actually fixed in pyrepl but there hasn't been a release in a while. I just bumped that project, so maybe we'll get a new release: https://bitbucket.org/pypy/pyrepl/issues/18/new-release

**Comment by blueyed** [comment]
`M-f` / `M-b` works by now.

**Comment by max-sixty** [comment]
I'm still having issues navigating in pdbpp. Neither Alt+arrow nor `Esc b` seem to work. (these work fine in other terminals). 

Is there an approach I could try to make these work? I'm frequently holding down arrow keys to navigate at the moment!

Thanks

**Comment by blueyed** [comment]
@max-sixty 
Does it work in bare `python`?
Which Python version and OS are you using?
I guess you should look around / step into the code in https://github.com/antocuni/pdb/blob/3ffc432dffd32d882aeb7b6834d254a521ca4877/pdb.py#L214-L216.

**Comment by max-sixty** [comment]
Yes it works in python fine - <A+arrow>, <C+a>, and `Esc b`  - all work. It also works in pdb.

I'm using both python2.7 & python 3.7 on MacOS in iTerm2. 
I just attempted to recreate a clean environment:

```sh
docker run -it python:2.7-stretch bash
pip install pdbpp
python -c "import pdb; pdb.set_trace()"  # keys don't work
python -c "import pdb; pdb.pdb.set_trace()"  # keys do work
```

Do others see different results?

Appreciate the response @blueyed

**Comment by blueyed** [comment]
@max-sixty 
Confirmed for python:2.7-stretch, but works with python:3.7-stretch (also with python:3.5-stretch).

With py37 it installs:
```
fancycompleter==0.8
pdbpp==0.9.6
Pygments==2.3.1
wmctrl==0.3
```

With py27 it installs:
```
fancycompleter==0.8
pdbpp==0.9.6
Pygments==2.3.1
pyrepl==0.8.4
virtualenv==16.4.0
wmctrl==0.3
```

Installing pyrepl with py37 still does not break it, apparently since pyrepl gets skipped there:
```
(Pdb++) from pyrepl import readline
*** ModuleNotFoundError: No module named '__builtin__'
```

fancycompleter instally pyrepl only for py2: https://bitbucket.org/antocuni/fancycompleter/src/22e3669eeeb48134ea6df1114ec7d70415d4cafc/setup.py?at=default&fileviewer=file-view-default#setup.py-12:13

Uninstalling pyrepl in py27 makes it work there also.
This appears to be https://bitbucket.org/pypy/pyrepl/pull-requests/10/fix-for-unmapped-key-combinations

pyrepl is in a sad state, and does not get installed on py3, because it does not work there.  See https://bitbucket.org/pypy/pyrepl/issues/20/fixes-for-py3-and-tox.

I am using an AUR package myself with a patch (https://aur.archlinux.org/packages/python-pyrepl-hg).
(The fix from https://bitbucket.org/pypy/pyrepl/pull-requests/10 does not appear to be necessary with it)

pyrepl is required for colors, after e.g. `import os; os.<tab>`.

**Comment by max-sixty** [comment]
Thank you so much for looking into this @blueyed !

For the moment, I'll uninstall `pyrepl` - I'd rather have the keys work than the colors. 

Shame about the state of pyrepl...
